- name: Adding repo key for MongoDB
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name:  Adding Mongo 3.4 Repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present
    filename: 'mongodb-org-3.4'

- name: Updating cache
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Start mongoDB and ensure enabled
  service:
    name: mongod
    state: started
    enabled: yes
